// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 9
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){












var __cegg;(function(){var a={};(function(a){__cegg=a;__cegg.a="cegg";__cegg.b=["nonGoogleScripts"];__cegg.isVendorTemplate=!0})(function(b){try{var d=b["19"];if(d)if(a.hasOwnProperty(d)&&!0===a[d])b["20"]();else{b[""]&&(w.CE_SNAPSHOT_NAME=b[""]);for(var c=d.toString();8>c.length;)c="0"+c;var e=c.replace(/(\d+)(\d{4})$/,"/pages/scripts/$1/$2.js");ea("//dnn506yrbagrg.cloudfront.net"+e+"?"+Math.floor((new Date).getTime()/
36E5),b["20"],b["21"]);a[d]=!0}else y(b["21"])}catch(f){y(b["21"])}})})();
var hb=this;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var ib=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,eb=function(a){if(null==a)return String(a);var b=ib.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},jb=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Na=function(a){if(!a||"object"!=eb(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!jb(a,"constructor")&&!jb(a.constructor.prototype,"isPrototypeOf"))return!1}catch(d){return!1}for(var b in a);return void 0===
b||jb(a,b)},kb=function(a,b){var d=b||("array"==eb(a)?[]:{}),c;for(c in a)if(jb(a,c)){var e=a[c];"array"==eb(e)?("array"!=eb(d[c])&&(d[c]=[]),d[c]=kb(e,d[c])):Na(e)?(Na(d[c])||(d[c]={}),d[c]=kb(e,d[c])):d[c]=e}return d};var Sa=null,lb=Math.random(),mb=null,Fa=null,cb=!1,nb={},ob={},db={};var pb,qb,rb,sb,tb,ub,vb,xb,yb,zb,Ab,Bb,S,Cb,Db,Eb,Fb,Gb,Hb,Ib,Jb,Kb,Lb,Mb,Nb,Ob,Pb,Rb,Sb,Tb,Ub,Vb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,id,jd,kd,ld,md,nd,od,qd,rd,sd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,
De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf,kf,lf,mf,nf,of,pf,qf,rf,sf,tf,zf;
(function(){var a=function(a){return{toString:function(){return a}}};pb=a("");qb=a("0");rb="";sb=a("");tb=a("");ub=a("");vb=a("");xb=a("");yb=a("");zb=a("");Ab=a("");Bb=a("2");S=a("3");Cb=a("");Db=a("");Eb=a("");
Fb=a("");Gb=a("");Hb=a("");Ib=a("");Jb=a("");Kb=a("");Lb=a("");Mb=a("");Nb=a("");Ob=a("");Pb=a("");Rb=a("");Sb=a("");Tb=a("");
Ub=a("");Vb=a("");Xb=a("");Yb=a("");Zb=a("");$b=a("");ac=a("4");bc=a("");cc=a("");dc=a("");ec=a("");fc=a("");gc=a("");hc=a("");ic=a("");jc=a("");kc=a("");
lc=a("");mc=a("");nc=a("");oc=a("");pc=a("");qc=a("");rc=a("");sc=a("");tc=a("");uc=a("5");vc=a("");wc=a("");xc=a("6");yc=a("");zc=a("");Ac=a("");Bc=a("");
Dc=a("");Ec=a("");Fc=a("");Gc=a("");Hc=a("7");Ic=a("");Jc=a("8");Kc=a("");Lc=a("");Mc=a("");Nc=a("");Oc=a("");Pc=a("");Qc=a("9");Rc=a("");Sc=a("");
Tc=a("");Uc=a("");Vc=a("");Wc=a("");Xc=a("");Yc=a("");Zc=a("");$c=a("");ad=a("");bd=a("");cd=a("");dd=a("10");ed=a("");fd=a("20");gd=a("21");hd=a("");id=a("");
jd=a("11");kd=a("");ld=a("");md=a("");nd=a("");od=a("");qd=a("12");rd=a("");sd=a("");wd=a("");xd=a("");yd=a("");zd=a("");Ad=a("");Bd=a("");Cd=a("");Dd=a("");Ed=a("13");Fd=a("");Gd=a("");
Hd=a("");Id=a("");Jd=a("");Kd=a("");Ld=a("");Md=a("");Nd=a("");Od=a("");Pd=a("");Qd=a("");Rd=a("");Sd=a("");Td=a("");Ud=a("");Vd=a("");Wd=a("15");Xd=a("");Yd=a("");Zd=a("");$d=a("");
ae=a("");be=a("");ce=a("");de=a("");ee=a("");fe=a("");ge=a("");he=a("");ie=a("");je=a("");ke=a("");le=a("");me=a("");ne=a("");oe=a("");pe=a("");qe=a("");re=a("");se=a("");
te=a("");ue=a("");ve=a("");we=a("");xe=a("");ye=a("");ze=a("");Ae=a("");Be=a("");Ce=a("");De=a("");Ee=a("");Fe=a("");Ge=a("");He=a("16");Ie=
a("");Je=a("");Ke=a("");Le=a("");Me=a("");Ne=a("");Oe=a("");Pe=a("");Qe=a("");Re=a("");Se=a("");Te=a("");Ue=a("");Ve=a("");We=a("");Xe=a("");Ye=a("");
Ze=a("");$e=a("");af=a("");bf=a("");cf=a("");df="";ef=a("");ff=a("");gf=a("");hf=a("");jf=a("");kf=a("17");lf=a("");mf=a("");nf=a("");of=a("");pf=a("");qf=
a("");rf=a("");sf=a("");tf=a("");zf=a("")})();var Ya=function(){},R=function(a){return"function"==typeof a},za=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},Af=function(a){return"number"==eb(a)&&!isNaN(a)},Bf=function(a){return/^[0-9]+$/.test(a)},Cf=function(a,b){if(Array.prototype.indexOf){var d=a.indexOf(b);return"number"==typeof d?d:-1}for(var c=0;c<a.length;c++)if(a[c]===b)return c;return-1},Ea=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},N=function(a){return Math.round(Number(a))||0},Ia=function(a){return"false"==
String(a).toLowerCase()?!1:!!a},Df=function(a){var b=[];if(za(a))for(var d=0;d<a.length;d++)b.push(String(a[d]));return b},K=function(){return new Date},Ka=function(a,b){if(!Af(a)||!Af(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},Ff=function(){this.prefix="gtm.";this.values={}};Ff.prototype.set=function(a,b){this.values[this.prefix+a]=b};Ff.prototype.get=function(a){return this.values[this.prefix+a]};Ff.prototype.contains=function(a){return void 0!==this.get(a)};
var Gf=function(a,b,d){try{if(!a[Jd])return a[dd](a,b||Ya,d||Ya);d&&d()}catch(c){}return!1},Hf=function(a,b){function d(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var c=Ea(b).split("&"),e=0;e<c.length;e++)if(c[e]){var f=c[e].indexOf("=");0>f?d(c[e],"1"):d(c[e].substring(0,f),c[e].substring(f+1))}},Jf=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},Kf=function(a){return function(){return a("GTM-WC5FXC")}},Lf=function(a){for(var b=0;b<a.length;b++)a[b]()},Ma=function(){return"gtm"+Mf()},
Mf=function(){var a=Sa.sequence||0;Sa.sequence=a+1;return a},Pa=function(a,b,d){return a&&a.hasOwnProperty(b)?a[b]:d},Nf=function(a){return null!==a&&void 0!==a&&void 0!==a.length},Of=function(a,b){0==b?a.Xa=!0:a.complete=!0;var d=a.g;a.s&&(a.s.Ha[d]=b);nb[d]&&(nb[d].state=b)},Pf=function(a,b){a.sort(function(a,c){return b(a,c)?-1:b(c,a)?1:0})};var w=window,M=document,Rf=navigator,bb=function(a,b){var d=w[a];w[a]=void 0===d?b:d;return w[a]},L=function(a,b,d,c){return(c||"http:"!=w.location.protocol?a:b)+d},Sf=function(a){var b=M.getElementsByTagName("script")[0]||M.body||M.head;b.parentNode.insertBefore(a,b)},Ra=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},r=function(a,b,d){var c=M.createElement("script");c.type="text/javascript";
c.async=!0;c.src=a;Ra(c,b);d&&(c.onerror=d);Sf(c);return c},ia=function(a,b){var d=M.createElement("iframe");d.height="0";d.width="0";d.style.display="none";d.style.visibility="hidden";Sf(d);Ra(d,b);void 0!==a&&(d.src=a);return d},F=function(a,b,d){var c=new Image(1,1);c.onload=function(){c.onload=null;b&&b()};c.onerror=function(){c.onerror=null;d&&d()};c.src=a},O=function(a,b,d,c){a.addEventListener?a.addEventListener(b,d,!!c):a.attachEvent&&a.attachEvent("on"+b,d)},y=function(a){w.setTimeout(a,
0)},Ua=!1,Va=[],Tf=function(a){if(!Ua){var b=M.createEventObject,d="complete"==M.readyState,c="interactive"==M.readyState;if(!a||"readystatechange"!=a.type||d||!b&&c){Ua=!0;for(var e=0;e<Va.length;e++)Va[e]()}Va.push=function(){for(var a=0;a<arguments.length;a++)y(arguments[a]);return 0}}},Uf=0,Vf=function(){if(!Ua&&140>Uf){Uf++;try{M.documentElement.doScroll("left"),Tf()}catch(a){w.setTimeout(Vf,50)}}},Aa=function(a){var b=M.getElementById(a);if(b&&ua(b,"id")!=a)for(var d=1;d<document.all[a].length;d++)if(ua(document.all[a][d],
"id")==a)return document.all[a][d];return b},ua=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},xa=function(a){return a.target||a.srcElement||{}},Da=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},ab=function(a){var b=M.createElement("div");b.innerHTML="A<div>"+a+"</div>";for(var b=b.lastChild,d=[];b.firstChild;)d.push(b.removeChild(b.firstChild));return d},
ya=function(a,b){for(var d={},c=0;c<b.length;c++)d[b[c]]=!0;for(var e=a,c=0;e&&!d[String(e.tagName).toLowerCase()]&&100>c;c++)e=e.parentElement;e&&!d[String(e.tagName).toLowerCase()]&&(e=null);return e},Wf=!1,Xf=[],Yf=function(){if(!Wf){Wf=!0;for(var a=0;a<Xf.length;a++)Xf[a]()}},Zf=function(a){a=a||w;var b=a.location.href,d=b.indexOf("#");return 0>d?"":b.substring(d+1)},Za=function(a){window.console&&window.console.log&&window.console.log(a)};var aa=function(a,b,d,c,e){var f,g=(a.protocol.replace(":","")||w.location.protocol.replace(":","")).toLowerCase();b&&(b=String(b).toLowerCase());switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||w.location.hostname).split(":")[0].toLowerCase();if(d){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:w.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=
f.split("/");0<=Cf(c||[],k[k.length-1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");if(e)a:{for(var l=f.split("&"),m=0;m<l.length;m++){var n=l[m].split("=");if(decodeURIComponent(n[0]).replace(/\+/g," ")==e){f=decodeURIComponent(n.slice(1).join("=")).replace(/\+/g," ");break a}}f=void 0}break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},Ha=function(a){var b="";if(a&&a.href)var d=a.href.indexOf("#"),b=0>d?a.href:a.href.substr(0,d);
return b},ba=function(a){var b=M.createElement("a");a&&(b.href=a);return b};var ja=function(a,b){var d=function(){};d.prototype=a.prototype;var c=new d;a.apply(c,Array.prototype.slice.call(arguments,1));return c};var ga=function(a,b,d){F(a,b,d)},ha=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var d=aa(ba(a),"host");if(!d)return!1;for(var c=0;b&&c<b.length;c++){var e=b[c]&&b[c].toLowerCase();if(e){var f=d.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&d.indexOf(e,f)==f)return!0}}return!1},Q=function(a,b,d){for(var c={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(d)&&(c[a[f][b]]=a[f][d],e=!0);return e?c:null};var $f=new Ff,ag={},cg={set:function(a,b){kb(bg(a,b),ag)},get:function(a){return T(a,2)},reset:function(){$f=new Ff;ag={}}},T=function(a,b){if(2==b){for(var d=ag,c=a.split("."),e=0;e<c.length;e++){if(void 0===d[c[e]])return;d=d[c[e]]}return d}return $f.get(a)},bg=function(a,b){for(var d={},c=d,e=a.split("."),f=0;f<e.length-1;f++)c=c[e[f]]={};c[e[e.length-1]]=b;return d};var dg=!1,eg=!1;var fg=Math.random(),gg="0.100000">fg;
var hg=function(a,b){if(gg){var d="//www.googletagmanager.com/a?id=GTM-WC5FXC&cv=9",c=function(a,b){b&&(d+=a+encodeURIComponent(b))};c("&v=","t");c("&n=",a);c("&s=",b&&b.state);c("&h=",b&&b.hideLatency);c("&g=",b&&b.gaLatency);c("&p=",b&&b.loadBy);c("&o=",b&&b.timeout);c("&l=",K().getTime()-N(mb));d+="&sr=0.100000";c("&ps=",fg);c("&cb=",Ka());F(d)}},ig=Ya,jg=function(){var a=!1;};var kg=Ya,lg=[],mg=!1,ca=function(a){return w["dataLayer"].push(a)},ng=function(a){var b=!1;return function(){!b&&R(a)&&y(Kf(a));b=!0}},tg=function(){for(var a=!1;!mg&&0<lg.length;){mg=!0;var b=lg.shift();if(R(b))try{b.call(cg)}catch(oa){}else if(za(b))a:{var d=b;if("string"==eb(d[0])){for(var c=d[0].split("."),e=c.pop(),f=d.slice(1),g=ag,h=0;h<c.length;h++){if(void 0===g[c[h]])break a;g=g[c[h]]}try{g[e].apply(g,f)}catch(oa){}}}else{var k=void 0,l=void 0,m=b;for(l in m)if(m.hasOwnProperty(l)){var n=
l,q=m[l];$f.set(n,q);kb(bg(n,q),ag)}var v=!1,z=m.event;if(z){if(!m.hasOwnProperty("gtm.uniqueEventId")){m["gtm.uniqueEventId"]=Mf();var t=m["gtm.uniqueEventId"];$f.set("gtm.uniqueEventId",t);kb(bg("gtm.uniqueEventId",t),ag)}k=m["gtm.uniqueEventId"];Fa=z;var x=ng(m.eventCallback),G=m.eventTimeout;G&&w.setTimeout(x,Number(G));v=kg(k,z,x,m.eventReporter)}mb||(mb=m["gtm.start"])&&ig();var C=m,B=k,E=z,H=ag;if(!v){var A=k,I=z;}Fa=null;a=v||a}var P=b,J=ag;sg();mg=!1}return!a},ug=function(){var a=tg();try{var b=w["dataLayer"].hide;if(b&&void 0!==b["GTM-WC5FXC"]&&b.end){b["GTM-WC5FXC"]=
!1;var d=!0,c;for(c in b)if(b.hasOwnProperty(c)&&!0===b[c]){d=!1;break}d&&(b.end(),b.end=null)}}catch(e){}return a},vg=function(){var a=bb("dataLayer",[]),b=bb("google_tag_manager",{}),b=b["dataLayer"]=b["dataLayer"]||{};Va.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Xf.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var d=a.push;a.push=function(){var b=[].slice.call(arguments,0);d.apply(a,b);for(lg.push.apply(lg,b);300<this.length;)this.shift();
return tg()};lg.push.apply(lg,a.slice(0));y(ug)};var wa=function(a,b,d){O(a,b,d,void 0)},ea=function(a,b,d){r(a,b,d)},Ga=function(a,b){return T(a,b||2)},fa=function(a,b){w[a]=b},p=function(a,b,d){var c=w;b&&(void 0===c[a]||d&&!c[a])&&(c[a]=b);return c[a]},u=function(a,b,d,c){return(c||"https:"==w.location.protocol?a:b)+d};var wg=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),xg={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},yg={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},zg=function(a,b){for(var d=[],c=0;c<a.length;c++)d.push(a[c]),d.push.apply(d,b[a[c]]||[]);return d},Ag=function(){var a=T("gtm.whitelist");
var b=a&&zg(Df(a),xg),d=T("gtm.blacklist")||T("tagTypeBlacklist")||[];wg.test(w.location&&w.location.hostname)&&(d=Df(d),d.push("nonGooglePixels","nonGoogleScripts"));var c=d&&zg(Df(d),yg),e={};return function(f){var g=f&&f[dd];if(!g)return!0;if(void 0!==e[g.a])return e[g.a];var h=!0;if(a)a:{if(0>Cf(b,g.a))if(g.b&&0<g.b.length)for(var k=0;k<g.b.length;k++){if(0>Cf(b,
g.b[k])){h=!1;break a}}else{h=!1;break a}h=!0}var l=!1;if(d){var m;if(!(m=0<=Cf(c,g.a)))a:{for(var n=g.b||[],q=new Ff,v=0;v<c.length;v++)q.set(c[v],!0);for(v=0;v<n.length;v++)if(q.get(n[v])){m=!0;break a}m=!1}l=m}return e[g.a]=!h||l}};var Ca=function(a){var b=M;return Bg?b.querySelectorAll(a):null},Cg=!1;if(M.querySelectorAll)try{var Dg=M.querySelectorAll(":root");Dg&&1==Dg.length&&Dg[0]==M.documentElement&&(Cg=!0)}catch(a){}var Bg=Cg;var _eu=function(a){var b=String(T("gtm.elementUrl")||a[Ac]||""),d=ba(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return Fa};_e.a="e";_e.b=["google"];var Ig=/(^|\.)doubleclick\.net$/i,Jg=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Ja=function(a){for(var b=String(M.cookie).split(";"),d=[],c=0;c<b.length;c++){var e=b[c].split("="),f=Ea(e[0]);if(f&&f==a){var g=Ea(e.slice(1).join("="));g&&(g=decodeURIComponent(g));d.push(g)}}return d},Kg=function(a,b,d,c,e){if(Ig.test(M.location.hostname)||"/"==d&&Jg.test(c))return!1;var f=a+"="+b+"; ";d&&(f+="path="+d+"; ");e&&(f+="expires="+e.toGMTString()+"; ");c&&(f+="domain="+c+";");var g=M.cookie;M.cookie=f;return g!=
M.cookie||0<=Cf(Ja(a),b)},Lg=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},Mg=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},Ng=function(){var a=aa(w.location,"host",!0).split(".");if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],d=a.length-2;0<=d;d--)b.push(a.slice(d).join("."));b.push("none");return b};var Og=function(a,b){this.f=a;this.j=b};Og.prototype.toString=function(){var a=""+this.f;1<this.j&&(a=a+"-"+this.j);return a};var Pg=function(a,b){this.Fa=a;this.ka=b};Pg.prototype.toString=function(){return""+this.ka+"."+this.Fa};var Sg=function(a,b){var d=new Qg(null,a,b);Rg(d);return d},Qg=function(a,b,d){this.Oa=Math.floor(K().getTime()/864E5);this.ja=b||"auto";this.aa=d||"/";var c=Lg(this.ja),e=Mg(this.aa);this.F=a||new Og(c,e);this.h=[];this.C=new Ff},Ug=function(a,b,d){b&&(""==d.Fa?Tg(a,b):(a.C.contains(b)||a.h.push(b),a.C.set(b,d)))},Vg=function(a,b){for(var d=0;d<b.length;d++)Ug(a,b[d][0],b[d][1])},Tg=function(a,b){var d=Cf(a.h,b);0<=d&&a.h.splice(d,1);a.C.set(b,void 0)},Wg=function(a){for(var b=[],d=0;d<a.h.length;d++){var c=
a.h[d];b.push([c,a.C.get(c)])}return b},Xg=function(a){for(var b=0,d=0;d<a.h.length;d++)b=Math.max(b,a.C.get(a.h[d]).ka);return 864E5*b};Qg.prototype.toString=function(){if(0==this.h.length)return"";for(var a=[],b=0;b<this.h.length;b++){var d=this.h[b];a.push(""+d+"."+this.C.get(d).toString())}return"GAX1."+this.F.toString()+"."+a.join("!")};
var Yg=function(a,b){for(var d=new Date,c=Mg(a.aa),e=[],f=0;f<a.h.length;f++){var g=a.h[f];a.C.get(g).ka<a.Oa&&e.push(g)}for(f=0;f<e.length;f++)Tg(a,e[f]);if(a.h.length>(b||10))return!1;d.setTime(Xg(a));if("auto"!=a.ja)return Kg("_gaexp",a.toString(),a.aa,a.ja,d);for(var h=Ng(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.F=new Og(Lg(h[k]),c),Kg("_gaexp",a.toString(),a.aa,h[k],d)))return!0;return!1},Rg=function(a){for(var b=a.F.f,d=a.F.j,c=Ja("_gaexp"),e=[],f=0;f<c.length;f++){var g=Zg(a,c[f]);g&&e.push(g)}Pf(e,
function(a,c){var e=a.F,f=c.F;return e.f==f.f&&e.j==f.j?!1:e.f==b&&e.j==d?!0:f.f==b&&f.j==d?!1:e.f==b?f.f!=b||e.j<f.j:f.f==b?!1:e.j==d?f.f!=b&&(f.j!=d||e.f<f.f):f.j==d?!1:e.f<f.f||e.f==f.f&&e.j<f.j});a.F=0<e.length?e[0].F:new Og(b,d);for(f=e.length-1;0<=f;f--)Vg(a,Wg(e[f]))},Zg=function(a,b){var d=b.match(/GAX1\.([^.]+).(.*)/);if(d){var c;a:{var e=(d[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=Ea(e[0]);if(0!=f.length){var g=2==e.length?Ea(e[1]):"1";if(Bf(f)&&Bf(g)){c=new Og(N(f),N(g));
break a}}}c=void 0}if(c){for(var h=new Qg(c,a.ja,a.aa),k=(d[2]||"").split("!"),l=0;l<k.length;l++){var m=k[l].split(".");if(3==m.length){if(!Bf(m[1]))return;Ug(h,m[0],new Pg(m[2],N(m[1])))}}return h}}};var _f=function(a){var b=String(T("gtm.referrer")||M.referrer);if(!b)return b;var d=ba(b);return b};_f.a="f";_f.b=["google"];var ch=function(a){var b=w.location,d;(d=a[pc]?a[pc]:T("gtm.url"))&&(b=ba(String(d)));var c=b.href,e=c.indexOf("#"),f=0>e?c:c.substr(0,e);a[ac]&&(f=aa(b,a[ac],a[Be],a[zc],a[oe]));return f},_u=ch;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a[Bb])==String(a[S])};_eq.a="eq";_eq.b=["google"];var La=new String("undefined"),Wa=function(a){this.resolve=function(b){for(var d=[],c=0;c<a.length;c++)d.push(a[c]===La?b:a[c]);return d.join("")}};Wa.prototype.toString=function(){return this.resolve("undefined")};Wa.prototype.valueOf=Wa.prototype.toString;var mh={},Xa=function(a,b){var d=Mf();mh[d]=[a,b];return d},nh=function(a){var b=a?0:1;return function(a){var c=mh[a];if(c&&R(c[b]))c[b]();mh[a]=void 0}};var oh=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},ph=function(a,b){return a<b?-1:a>b?1:0};var qh;a:{var rh=hb.navigator;if(rh){var sh=rh.userAgent;if(sh){qh=sh;break a}}qh=""}var U=function(a){return-1!=qh.indexOf(a)};var th=function(){U("iPod")},uh=function(){return U("iPhone")&&!U("iPod")&&!U("iPad")};var vh=function(a){vh[" "](a);return a};vh[" "]=function(){};var xh=function(a,b){var d=wh;return Object.prototype.hasOwnProperty.call(d,a)?d[a]:d[a]=b(a)};var yh=U("Opera"),zh=U("Trident")||U("MSIE"),Ah=U("Edge"),Bh;if(Bh=U("Gecko"))Bh=!(-1!=qh.toLowerCase().indexOf("webkit")&&!U("Edge"));var Ch=Bh&&!(U("Trident")||U("MSIE"))&&!U("Edge"),Dh=-1!=qh.toLowerCase().indexOf("webkit")&&!U("Edge");Dh&&U("Mobile");U("Macintosh");U("Windows");U("Linux")||U("CrOS");var Eh=hb.navigator||null;Eh&&(Eh.appVersion||"").indexOf("X11");U("Android");uh();U("iPad");th();uh()||U("iPad")||th();var Fh=function(){var a=hb.document;return a?a.documentMode:void 0},Gh;
a:{var Hh="",Ih=function(){var a=qh;if(Ch)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Ah)return/Edge\/([\d\.]+)/.exec(a);if(zh)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Dh)return/WebKit\/(\S+)/.exec(a);if(yh)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Ih&&(Hh=Ih?Ih[1]:"");if(zh){var Jh=Fh();if(null!=Jh&&Jh>parseFloat(Hh)){Gh=String(Jh);break a}}Gh=Hh}
var Kh=Gh,wh={},Lh=function(a){return xh(a,function(){for(var b=0,d=oh(String(Kh)).split("."),c=oh(String(a)).split("."),e=Math.max(d.length,c.length),f=0;0==b&&f<e;f++){var g=d[f]||"",h=c[f]||"";do{var k=/(\d*)(\D*)(.*)/.exec(g)||["","","",""],l=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==l[0].length)break;b=ph(0==k[1].length?0:parseInt(k[1],10),0==l[1].length?0:parseInt(l[1],10))||ph(0==k[2].length,0==l[2].length)||ph(k[2],l[2]);g=k[3];h=l[3]}while(0==b)}return 0<=b})},Mh;
var Nh=hb.document;Mh=Nh&&zh?Fh()||("CSS1Compat"==Nh.compatMode?parseInt(Kh,10):5):void 0;var Oh;if(!(Oh=!Ch&&!zh)){var Ph;if(Ph=zh)Ph=9<=Number(Mh);Oh=Ph}Oh||Ch&&Lh("1.9.1");zh&&Lh("9");var $a=function(a,b){var d="";zh&&!Qh(a)&&(d='<script>document.domain="'+document.domain+'";\x3c/script>'+d);var c="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+d+"</head><body>"+b+"</body></html>";if(Rh)a.srcdoc=c;else if(Sh){var e=a.contentWindow.document;e.open("text/html","replace");e.write(c);e.close()}else Th(a,c)},Rh=Dh&&"srcdoc"in document.createElement("iframe"),Sh=Ch||Dh||zh&&Lh(11),Th=function(a,b){zh&&Lh(7)&&!Lh(10)&&6>Uh()&&Vh(b)&&(b=Wh(b));var d=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};zh&&!Qh(a)?Xh(a,d):d()},Uh=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},Qh=function(a){try{var b;var d=a.contentWindow;try{var c;if(c=!!d&&null!=d.location.href)b:{try{vh(d.foo);c=!0;break b}catch(e){}c=!1}b=c}catch(e){b=!1}return b}catch(e){return!1}},Yh=0,Xh=function(a,b){var d="goog_rendering_callback"+Yh++;hb[d]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+d+";window.parent."+d+" = null;continuation();})()\x3c/script>'"},Vh=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},Wh=function(a){for(var b=unescape(encodeURIComponent(a)),d=Math.floor(b.length/2),c=[],e=0;e<d;++e)c[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(c[d]=b.charAt(b.length-1));return c.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var $h=function(a,b,d,c){return function(){try{if(0<b.length){var e=b.shift(),f=$h(a,b,d,c);if("SCRIPT"==String(e.nodeName).toUpperCase()&&"text/gtmscript"==e.type){var g=M.createElement("script");g.async=!1;g.type="text/javascript";g.id=e.id;g.text=e.text||e.textContent||e.innerHTML||"";e.charset&&(g.charset=e.charset);var h=e.getAttribute("data-gtmsrc");h&&(g.src=h,Ra(g,f));a.insertBefore(g,null);h||f()}else if(e.innerHTML&&0<=e.innerHTML.toLowerCase().indexOf("<script")){for(var k=[];e.firstChild;)k.push(e.removeChild(e.firstChild));
a.insertBefore(e,null);$h(e,k,f,c)()}else a.insertBefore(e,null),f()}else d()}catch(l){y(c)}}};var bi=function(a,b,d){if(M.body){var c=
a[jd];c instanceof Wa&&(c=c.resolve(Xa(b,d)),b=Ya);if(a[lf])try{$a(ia(),"<script>var google_tag_manager=parent.google_tag_manager;\x3c/script>"+c),y(b)}catch(e){y(d)}else a[nf]?ai(c,b,d):$h(M.body,ab(c),b,d)()}else w.setTimeout(function(){bi(a,b,d)},200)},_html=bi;_html.a="html";_html.b=["customScripts"];
var ni=function(a,b,d,c,e){var f=a+"{"+(b+": "+d+(c?" !important":""))+"}";e&&(f=e+"{"+f+"}");var g=document;if(g.createStyleSheet){var h=ki(g),k=h.rules.length;h.insertRule(f,k);return function(){h.deleteRule?h.deleteRule(k):h.removeRule(k);h.insertRule("x {}",k)}}var l=li(f,g);mi(l,g);var m=l.parentNode;return function(){m.removeChild(l)}},oi=null,ki=function(a){if(oi)return oi;for(var b=a.styleSheets.length-1;0<=b;b--){var d=a.styleSheets[b],c=d.ownerNode;if(c&&c.parentNode&&"HEAD"==c.parentNode.tagName)return oi=
d}0==a.styleSheets.length&&a.createStyleSheet();return oi=a.styleSheets[0]},li=function(a,b){var d=(b||document).createElement("style");void 0!==d.cssText?d.cssText=a:d.innerHTML=a;return d},mi=function(a,b){var d=b||document,c=d.getElementsByTagName("head")[0];c||(c=d.createElement("head"),d.body.parentNode.insertBefore(c,d.body));c.appendChild(a)};var vi={},wi=void 0,xi=function(a){var b=vi[a];b||(b={id:a,v:[],W:0,Ia:null,za:void 0,Da:!1},vi[a]=b);wi=b},zi=function(a,b,d,c){var e=wi;if(!Bg||!e)return!1;var f={id:e.id+":"+e.v.length,fb:b,U:[],$a:d,G:a,ua:0,sa:c||null,Na:0,V:!1};e.v.push(f);null===a?(f.V=!0,b(null)):yi(e);return!0},Ai=function(a){var b=ni(a,"visibility","hidden",!0);return function(){R(b)&&b.apply();b=null}},Bi=function(a,b,d,c){var e=b;if(!Ua){var f=Ai(a.A);Va.push(f);e=function(a,c){var d=b(a,c);f();return d}}return zi(a,e,
d,c)},yi=function(a){if(!a.Da){for(var b=a.W;b<a.v.length;b++){var d=a.v[b],c=b==a.W;if(!d.V&&!Ci(c,d))break;d.V&&c&&a.W++}a.v.length>a.W?(a.Ia||(a.Ia=w.setTimeout(function(){a.Ia=null;yi(a)},80)),Ua||a.za||(a.za=function(){y(function(){yi(a)})},O(M,"DOMContentLoaded",a.za))):Di(a)}},Di=function(a){for(var b=0;b<a.v.length;b++){var d=a.v[b];if(d.G)for(var c=Ca(d.G.A)||[],e=0;e<c.length;e++){var f=c[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[d.id]||(Ei(f,d.id),d.U.push(Fi(f,d.id)))}}},Ci=
function(a,b){var d=[];if(b.G){var c=Gi(b.G,b.id),e=null;b.sa&&(e=Gi(b.sa,b.id+"-t"));for(var f=0;f<c.length;f++){var g=c[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!Ua&&(null===b.sa.o||b.Na+d.length<b.sa.o)))break;d.push({element:g,Jb:h})}}if(!Ua&&b.$a&&(!a||null==b.G.o||b.G.o!=b.ua+d.length))return!1;for(var k=0;k<d.length;k++){var l=d[k].element,m=d[k].Jb,n;b.ua++;Ei(l,b.id);m&&(b.Na++,n=b.id+"-t",Ei(m,n));var q=b.fb(l,m);R(q)&&b.U.push(q);b.U.push(Fi(l,b.id));m&&n&&b.U.push(Fi(m,n))}if(b.G.o&&
b.G.o==b.ua||Ua)b.V=!0;return!0},Ei=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},Fi=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},Gi=function(a,b){for(var d=Ca(a.A)||[],c=[],e=0;e<d.length;e++){var f=d[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.D&&!Hi(f))break;c.push(f)}}return c},Hi=function(a){if(Ua)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var ka,Ii,Ji,sa=/(Firefox\D28\D)/g.test(Rf.userAgent),Li=function(a,b){return function(d){d=d||w.event;var c=xa(d),e=!1;if(3!==d.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(c=ya(c,["a","area"]),e=!c||!c.href||Ki(c.href)||2===d.which||null==d.which&&4==d.button||d.ctrlKey||d.shiftKey||d.altKey||!0===d.metaKey);var f="FORM_SUBMIT"==a?ka:Ji;if(d.defaultPrevented||!1===d.returnValue||d.X&&d.X()){if(c){var g={simulateDefault:!1},h=la(f,["wnc","nwnc"]);h&&ma(a,c,g,f.wt,h)}}else{if(c){var g={},k,l=la(f,["wnc",
"nwnc","nwc","wc"]);(k=ma(a,c,g,f.wt,l))||(na(g.eventReport,f)?b=!0:e=!0);e=e||k||"LINK_CLICK"==a&&sa;g.simulateDefault=!k&&b&&!e;g.simulateDefault&&(e=va(c,g)||e,!e&&d.preventDefault&&d.preventDefault());d.returnValue=k||!b||e;return d.returnValue}return!0}}}},ma=function(a,b,d,c,e){var f=c||2E3,g={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||ua(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event="gtm.linkClick";
g["gtm.elementUrl"]=b.href;g.eventTimeout=f;g.eventCallback=Mi(b,d);g.eventReporter=function(a){d.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=e||"";g.event="gtm.formSubmit";g["gtm.elementUrl"]=Ni(b);g.eventTimeout=f;g.eventCallback=Oi(b,d);g.eventReporter=function(a){d.eventReport=a};break;case "CLICK":g.event="gtm.click";g["gtm.elementUrl"]=(b.attributes&&b.attributes.formaction?b.formAction:"")||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return ca(g)},Ni=
function(a){var b=a.action;b&&b.tagName&&(b=a.cloneNode(!1).action);return b},ra=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},va=function(a,b){var d=!1,c=/(iPad|iPhone|iPod)/g.test(Rf.userAgent),e=ra(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);b.targetWindow=w.frames&&w.frames[f]||w[f];break;case "_blank":c?(b.simulateDefault=!1,d=!0):(b.targetWindowName=
"gtm_autoEvent_"+K().getTime(),b.targetWindow=w.open("",b.targetWindowName));break;default:c&&!w.frames[e]?(b.simulateDefault=!1,d=!0):(w.frames[e]||(b.targetWindowName=e),b.targetWindow=w.frames[e]||w.open("",e))}return d},Mi=function(a,b,d){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(d=d||K().getTime(),500>K().getTime()-d&&w.setTimeout(Mi(a,b,d),25)))}},Oi=function(a,b,d){return function(){if(b.simulateDefault)if(b.targetWindow){var c;b.targetWindowName&&
(c=a.target,a.target=b.targetWindowName);M.gtmSubmitFormNow=!0;pa(a).call(a);b.targetWindowName&&(a.target=c)}else d=d||K().getTime(),500>K().getTime()-d&&w.setTimeout(Oi(a,b,d),25)}},la=function(a,b){for(var d=[],c=0;c<b.length;c++){var e=a[b[c]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&d.push(f)}return d.join(",")},Pi=function(a,b,d,c,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;f="0"}var g=a.wt;b&&(!g||g>c)&&(a.wt=c);a[b?d?"wc":"wnc":d?"nwc":"nwnc"][f]=!0},na=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;
for(var d=0;d<Qi.length;d++)if(a.passingRules[d]){var c=Ri[d],e=c&&c[0]&&c[0][0]||c[1]&&c[1][0];if(e&&"0"!=e&&(b.wc[e]||b.wnc[e]))for(var f=Qi[d][1],g=0;g<f.length;g++)if(a.resolvedTags[f[g]])return!0}return!1},Ba=function(a,b,d,c,e){var f,g,h=!1;switch(a){case "CLICK":if(M.gtmHasClickListenerTag)return;M.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=xa(a);b&&ma("CLICK",b,{},c)};h=!0;break;case "LINK_CLICK":b&&!Ii&&(Ii=Ha(M.location));Pi(Ji,b||!1,d||!1,c,e);if(M.gtmHasLinkClickListenerTag)return;
M.gtmHasLinkClickListenerTag=!0;f="click";g=Li(a,b||!1);break;case "FORM_SUBMIT":Pi(ka,b||!1,d||!1,c,e);if(M.gtmHasFormSubmitListenerTag)return;M.gtmHasFormSubmitListenerTag=!0;f="submit";g=Li(a,b||!1);break;default:return}O(M,f,g,h)},Ki=function(a){if(!Ii)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var d=ba(a);return Ii==Ha(d)},pa=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;
M.gtmFormElementSubmitter||(M.gtmFormElementSubmitter=M.createElement("form"));return M.gtmFormElementSubmitter.submit.call?M.gtmFormElementSubmitter.submit:a.submit},Si=function(){var a=function(a){var b=bb("google_tag_manager",{}),c=b[a];c||(c=b[a]={},c.nwnc={},c.nwc={},c.wnc={},c.wc={},c.wt=null,c.l=!1);return c};Ji=a("linkClickMap");ka=a("formSubmitMap")};var Qa=function(a,b){var d=b||hb,c=d.onerror,e=!1;Dh&&!Lh("535.3")&&(e=!e);d.onerror=function(b,d,h,k,l){c&&c(b,d,h,k,l);a({message:b,fileName:d,Ta:h,$b:k,error:l});return e}};var Pj=36,Qj=[],Rj=[],Sj=[],Tj=new Ff,Uj=[],Z=[],Qi=[],Ri=[],Vj=function(){this.L=[]};Vj.prototype.set=function(a,b){this.L.push([a,b]);return this};Vj.prototype.resolve=function(a,b){for(var d={},c=0;c<this.L.length;c++){var e=Wj(this.L[c][0],a,b),f=Wj(this.L[c][1],a,b);d[e]=f}return d};var Xj=function(a){this.index=a};Xj.prototype.resolve=function(a,b){var d=Sj[this.index];if(d&&!b(d)){var c=d[qd];if(a){if(a.get(c))return;a.set(c,!0)}d=Wj(d,a,b);a&&a.set(c,!1);return Gf(d)}};
var _M=function(a){return new Xj(a)},Yj=function(a){this.resolve=function(b,d){for(var c=[],e=!1,f=0;f<a.length;f++){var g=Wj(Qj[a[f]],b,d);g===La&&(e=!0);c.push(g)}return e?new Wa(c):c.join("")}},_T=function(a){return new Yj(arguments)},Zj=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=
function(d,c){var e=Wj(a[0],d,c);if(a[0]instanceof Xj&&b(8)&&b(16)){if(e===La)return e;var f=Ma();Tj.set(f,e);return'google_tag_manager["GTM-WC5FXC"].macro(\''+f+"')"}for(var e=String(e),g=1;g<a.length;g++)e=X[a[g]](e);return e}},_E=function(a,b){return new Zj(arguments)},ak=function(a,b){this.w=a;this.ra=b},_R=function(a,b){return new ak(a,b)},Wj=function(a,b,d){var c=a;if(a instanceof Xj||a instanceof Vj||a instanceof Yj||a instanceof Zj)return a.resolve(b,d);if(!(a instanceof ak))if(za(a))for(var c=
[],e=0;e<a.length;e++)c[e]=Wj(a[e],b,d);else if(a&&"object"==typeof a){var c={},f;for(f in a)a.hasOwnProperty(f)&&(c[f]=Wj(a[f],b,d))}return c},ck=function(){for(var a=[_eq,_e,'_event',_M(0),'gtm.js','2345993_2147479553',_ua,true,'UA-3005683-1',false,'\x26tid',{10:8},2,__cegg,'1','00607559',4,_html,'\n\x3cscript type\x3d\x22text/gtmscript\x22\x3e!function(b,e,f,g,a,c,d){b.fbq||(a\x3db.fbq\x3dfunction(){a.callMethod?a.callMethod.apply(a,arguments):a.queue.push(arguments)},b._fbq||(b._fbq\x3da),a.push\x3da,a.loaded\x3d!0,a.version\x3d\x222.0\x22,a.queue\x3d[],c\x3de.createElement(f),c.async\x3d!0,c.src\x3dg,d\x3de.getElementsByTagName(f)[0],d.parentNode.insertBefore(c,d))}(window,document,\x22script\x22,\x22https://connect.facebook.net/en_US/fbevents.js\x22);fbq(\x22init\x22,\x221171922536217284\x22);fbq(\x22track\x22,\x22PageView\x22);\x3c/script\x3e\n\x3cnoscript\x3e\x3cimg height\x3d\x221\x22 width\x3d\x221\x22 style\x3d\x22display:none\x22 src\x3d\x22https://www.facebook.com/tr?id\x3d1171922536217284\x26amp;ev\x3dPageView\x26amp;noscript\x3d1\x22\x3e\x3c/noscript\x3e\n\n\n',1,'\x3cscript type\x3d\x22text/gtmscript\x22\x3epiAId\x3d\x2267842\x22;piCId\x3d\x221540\x22;(function(){function a(){var b\x3ddocument.createElement(\x22script\x22);b.type\x3d\x22text/javascript\x22;b.src\x3d(\x22https:\x22\x3d\x3ddocument.location.protocol?\x22https://pi\x22:\x22http://cdn\x22)+\x22.pardot.com/pd.js\x22;var a\x3ddocument.getElementsByTagName(\x22script\x22)[0];a.parentNode.insertBefore(b,a)}window.attachEvent?window.attachEvent(\x22onload\x22,a):window.addEventListener(\x22load\x22,a,!1)})();\x3c/script\x3e',3,_u,'Page URL','Page Hostname','host','Page Path','path',_f,'Referrer','Event'],b=[],d=0;d<a.length;d++)b[d]=bk(d,a);return b},bk=function(a,b){var d=b[a],c=d;if(d instanceof Xj||d instanceof Zj||d instanceof Yj||d instanceof ak)c=d;else if(za(d))for(var c=[],e=0;e<d.length;e++)c[e]=bk(d[e],b);else if("object"==typeof d){var c=new Vj,f;for(f in d)d.hasOwnProperty(f)&&c.set(b[f],
bk(d[f],b))}return c},ek=function(a,b){for(var d=b?b.split(","):[],c=0;c<d.length;c++){var e=d[c]=d[c].split(":");0==a&&(e[1]=Qj[e[1]]);if(1==a)for(var f=dk(e[0]),e=d[c]={},g=0;g<f.length;g++){var h=Rj[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=dk(e[g]);3==a&&(d[c]=Qj[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=Qj[e[g][k]]}else e[g]=[];5==a&&(d[c]=e[0])}return d},dk=function(a){var b=[];if(!a)return b;for(var d=0,c=0;c<a.length&&d<Pj;d+=
6,c++){var e=a&&a.charCodeAt(c)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&f&&b.push(d);2&f&&b.push(d+1);4&f&&b.push(d+2);8&f&&b.push(d+3);16&f&&b.push(d+4);32&f&&b.push(d+5)}}return b},fk=function(a,b,d){a.push.apply(a,ek(b,d))};
var pg=function(){},nk=function(a){},sg=function(){},ok=function(a){},pk=function(a,b){},qk=function(a,b){},qg=function(a){};var rk,sk;
var Ek=function(a){return function(){}},Fk=function(a){return function(){}};var Gk=function(a){var b=this;this.g=a;this.complete=this.Xa=!1;this.qa=[];this.la=[];this.S=function(){if(b.s&&b.s.event){var d=b.s.event,c=b.g;}b.complete||Lf(b.qa);Of(b,1);if(ob[a])for(var e=0;e<ob[a].length;e++)ob[a].shift().S()};this.R=function(){if(b.s&&b.s.event){var d=b.s.event,c=b.g;}b.complete||
Lf(b.la);Of(b,2);if(ob[a])for(var e=0;e<ob[a].length;e++)ob[a].shift().R()};this.B=Ya},Hk=function(a,b){a.qa.push(b)},Ik=function(a,b){a.la.push(b)},Jk=function(a){this.M=[];this.Ga=[];this.Pa={};this.ya=[];this.Y=0;this.Wa={};this.Ya={};this.Ha={};this.event=a};Jk.prototype.addListener=function(a){this.ya.push(a)};
var Kk=function(a,b,d,c,e,f){if(!d.complete){a.M[b]=d;void 0==c&&(c=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);c=za(c)?c.slice():["or",c];e=za(e)?e.slice():[e];f=za(f)?f.slice():[f];a.Pa[b]=c;a.Wa[b]=0<e.length;a.Ya[b]=0<f.length;a.Y++;var g=function(){0<a.Y&&a.Y--;0<a.Y||Lf(a.ya)};Hk(d,g);Ik(d,g)}},Lk=function(a,b,d){a.M[b]&&(Hk(a.M[b],function(){d(b,!0)}),Ik(a.M[b],function(){d(b,!1)}))},Mk=function(a,b){var d=Ya,c=!1;return function(e,f){var g;a:{for(var h=0;h<a.length;h++)if(a[h]instanceof ak&&a[h].w===
e||a[h]===e){g=h;break a}g=-1}c||0>g||("or"==a[0]?f?(c=!0,b()):(a.splice(g,1),1==a.length&&(c=!0,d())):f?(a.splice(g,1),1==a.length&&(c=!0,b())):(c=!0,d()))}},Qk=function(a,b){var d=[],c=!1,e=function(b){var f,g,h=Z[b];if(a.event.c(h)){}else g=Nk(h,b,a);if(f=g){var k=Ok(b,!0);0<k.length&&e(k[0].w);d.push(f);var l=Ok(b,!1);0<l.length&&e(l[0].w)}else c=
!0};e(b);if(!c){for(var f=0;f<d.length;f++){var g=d[f],h=Ok(g.g,!0);if(0<h.length){var k=d[f-1],l=Pk(g);Hk(k,l);0==h[0].ra&&Ik(k,l)}var m=Ok(g.g,!1);0<m.length&&(l=Pk(d[f+1]),Hk(g,l),0==m[0].ra&&Ik(g,l))}a.Ga.push(d)}},Ok=function(a,b){var d=b?ye:Pe,c=Z[a],e=void 0===c[d]?[]:c[d];return za(e)?e:[e]},Pk=function(a){return function(){a.B()}},Sk=function(a){for(var b={},d=0;d<a.length;d++){var c=a[d],e=[],f=function(a){var b=Ok(a,!0);0<b.length&&f(b[0].w);e.push(a);var c=Ok(a,!1);0<c.length&&f(c[0].w)};
f(c.g);b[c.g]=e}Rk(a,b);return b},Rk=function(a,b){for(var d=0;d<a.length;d++){var c=a[d].g,e;for(e in b)if(b.hasOwnProperty(e)&&e!=c&&-1<Cf(b[e],c)){delete b[c];break}}};var Uk=function(a,b){return function(){a[fd]=b.S;a[gd]=b.R;var d=b.g,c=b.s&&b.s.Ha[d],e=nb[d]&&nb[d].state,f=c?void 0!==c:b.Xa||b.ac,g=nb[d]&&nb[d].firingOption,h=g&&2==g,k=g&&1==g;if(!f&&void 0===e||!f&&!h||!h&&!k){Of(b,0);var l=b.s?b.s.event:void 0;a=Tk(a,l?l.c:Ag());if(l){var m=a;pk(l,d)}Gf(a,b.S,b.R)}else h&&0==e||k&&0==c?ob[d].push(b):h&&1==e||k&&1==c?b.S():b.R()}},Tk=function(a,b){a=Wj(a,new Ff,b);return a},Nk=function(a,b,d){var c=new Gk(b);c.s=d;Hk(c,Ek(a));Ik(c,Fk(a));c.B=Uk(a,c);return c};
var Yk=!1,_ua=function(a,b,d){function c(a){var b=[].slice.call(arguments,0);b[0]=n+b[0];w[l()].apply(window,b)}function e(b,d){void 0!==a[d]&&c("set",b,a[d])}function f(a,b){return void 0===b?b:a(b)}function g(a,b){if(b)for(var d in b)b.hasOwnProperty(d)&&c("set",a+d,b[d])}function h(){var b=function(a,b,d){if(!Na(b))return!1;for(var e=Pa(Object(b),d,[]),f=0;e&&f<e.length;f++)c(a,e[f]);return!!e&&0<e.length},d;a[Jc]?d=T("ecommerce"):
a[Ic]&&(d=a[Ic].ecommerce);if(!Na(d))return;d=Object(d);var e=Pa(a[ad],"currencyCode",d.currencyCode);void 0!==e&&c("set","&cu",e);b("ec:addImpression",d,"impressions");if(b("ec:addPromo",d[d.promoClick?"promoClick":"promoView"],"promotions")&&d.promoClick){c("ec:setAction","promo_click",d.promoClick.actionField);return}for(var f="detail checkout checkout_option click add remove purchase refund".split(" "),g=0;g<f.length;g++){var h=d[f[g]];if(h){b("ec:addProduct",h,"products");c("ec:setAction",f[g],
h.actionField);break}}}function k(a,b,c){var d=0;if(void 0!==a)for(var e in a)if(a.hasOwnProperty(e)&&(c&&z[e]||!c&&void 0===z[e])){var f=t[e]?Ia(a[e]):a[e];"anonymizeIp"!=e||f||(f=void 0);b[e]=f;d++}return d}bb("GoogleAnalyticsObject",a[Pd]||"ga");var l=function(){return w.GoogleAnalyticsObject},m=bb(l(),function(){var a=w[l()];a.q=a.q||[];a.q.push(arguments)});m.l=Number(K());var n="",q="";"string"!=typeof a[bf]?(q=Ma(),n=q+"."):""!==
a[bf]&&(q=a[bf],n=q+".");var v=!1;
var x={name:q};m("create",a[qb],x);c("set","&gtm","GTM-WC5FXC");var C;a[Ed]&&c("require","linkid","linkid.js");c("set","hitCallback",function(){if(R(a[hd]))a[hd]();else{var c=a[ad],d=c&&c.hitCallback;R(d)&&d()}b()});if(a[Ye]){}else if(a[Ze]){}else if(a[af]){}else if(a[$e]){}else if(a[yc]){}else if(a[wc]){}else if(a[Xe]){}else{a[Qc]&&(c("require","ec","ec.js"),h());if(a[Hc]&&!a[Sc]){var J="_dc_gtm_"+String(a[qb]).replace(/[^A-Za-z0-9-]/g,"");c("require","displayfeatures",void 0,{cookieName:J})}C?c("send","pageview",C):c("send","pageview");}if(!Yk){var V=a[uc]?"u/analytics_debug.js":"analytics.js";a[rd]&&!a[uc]&&(V="internal/"+V);
Yk=!0;r(L("https:","http:","//www.google-analytics.com/"+V,v),function(){w[l()].loaded||d()},d)}};_ua.a="ua";_ua.b=["google"];var Zk=function(){var a=[];return function(b,d){if(void 0===a[b]){var c=Uj[b]&&Wj(Uj[b],new Ff,d),e=c;if(c)if(c[Ab]&&za(c[S]))for(var f=c[S],e=!1,g=0;!e&&g<f.length;g++)c[S]=f[g],e=Gf(c);else e=Gf(c);a[b]=[e,c]}return a[b]}},mk=function(a,b){for(var d=b[0],c=0;c<d.length;c++)if(!a.P(d[c],a.c)[0])return!1;for(var e=b[2],c=0;c<e.length;c++)if(a.P(e[c],a.c)[0])return!1;return!0},$k=!1,kg=function(a,b,d,c){switch(b){case "gtm.js":if($k)return!1;$k=!0;break;case "gtm.sync":if(T("gtm.snippet")!=lb)return!1}T("tagTypeBlacklist");
for(var e={id:a,name:b,ha:d||Ya,fa:dk(),pa:dk(),P:Zk(),c:Ag()},f=[],g=0;g<Qi.length;g++)if(mk(e,Qi[g])){f[g]=!0;for(var h=e,k=Qi[g],l=k[1],m=0;m<l.length;m++)h.fa[l[m]]=!0;for(var n=k[3],m=0;m<n.length;m++)h.pa[n[m]]=!0}else f[g]=!1;pk(e);var v=[];for(var z=0;z<Pj;z++)if(e.fa[z]&&!e.pa[z])if(e.c(Z[z])){}else{v[z]=Z[z];}e.T=v;for(var t=new Jk(e),x=0;x<Pj;x++)if(e.fa[x]&&!e.pa[x])if(e.c(Z[x])){}else{var G=e.T[x],C=Nk(G,x,t);Kk(t,x,C,G[Bc],G[ye],G[Pe]);if(G[pb])break}t.addListener(e.ha);for(var B=[],
E=0;E<t.M.length;E++){var H=t.M[E];if(H){var D=t.Pa[E],A=t.Wa[E],I=t.Ya[E];if(0!=D.length||A||I){if(0<D.length)for(var P=Mk(D,H.B),J=0;J<D.length;J++)D[J]instanceof ak&&D[J].w!=E&&Lk(t,D[J].w,P);(A||I)&&Qk(t,E)}else B.push(E)}}for(E=0;E<B.length;E++)t.M[B[E]].B();for(E=0;E<t.Ga.length;E++){for(var oa=t.Ga[E],V=void 0,W=oa,qa=[],wb=0;wb<W.length;wb++){var gb=W[wb],Wb=gb.g,Ef=nb[Wb],td=Ef.firingOption;0!=td&&(1==td&&void 0!==gb.s.Ha[Wb]||2==td&&void 0!==Ef.state)&&qa.push(gb)}var ud=Sk(qa);for(V in ud)if(ud.hasOwnProperty(V)){for(var vd=
void 0,If=void 0,Cc=ud[V],bl=Cc[0],ij=Cc[Cc.length-1],jj,Oa=0;Oa<W.length;Oa++){var pd=W[Oa];!vd&&pd.g==bl&&0<Oa&&(vd=W[Oa-1]);pd.g==ij&&Oa<W.length-1&&(If=W[Oa+1]);if(-1<Cf(Cc,pd.g))if(jj=W.splice(Oa,1)[0],pd.g==ij)break;else Oa--}if(jj){var kj=Number(V),ta=vd,uf=If;if(ta){var cl=ta.qa[0],dl=ta.la[0],lj=ta;lj.qa=[];lj.la=[];Hk(ta,cl);Ik(ta,dl)}if(ta&&uf){var vf=Pk(uf);Hk(ta,vf);var wf=Ok(ta.g,!1);0<wf.length&&wf[0].w!=kj&&0==wf[0].ra&&Ik(ta,vf);var xf=Ok(uf.g,!0);0<xf.length&&xf[0].w!=kj&&0==xf[0].ra&&
Ik(ta,vf)}}}0<oa.length&&oa[0].B()}0<t.Y||Lf(t.ya);c&&R(c)&&c({passingRules:f,resolvedTags:e.T});
if("gtm.js"==b||"gtm.sync"==b)a:{}for(var oj in e.T)if(e.T.hasOwnProperty(oj)){var pj=e.T[oj],yf;if(!(yf=void 0==pj[qd])){var qj=pj[qd];yf=!("function"!=typeof String.prototype.startsWith?0===qj.indexOf("_implicit"):qj.startsWith("_implicit"))}if(yf)return!0}return!1};var el=function(){};var fl=function(){};var al={macro:function(a){if(Tj.contains(a))return Tj.get(a)}};al.dataLayer=cg;al.onHtmlSuccess=nh(!0);al.onHtmlFailure=nh(!1);al.callback=function(a){db.hasOwnProperty(a)&&R(db[a])&&db[a]();delete db[a]};
al.kb=function(){var a=w.google_tag_manager;a||(a=w.google_tag_manager={});if(a["GTM-WC5FXC"]){}else{a["GTM-WC5FXC"]=al;Sa=a;Si();Qj.push.apply(Qj,ck());fk(Rj,0,"10:0,10:1,12:2,2:3,3:4,10:6,15:7,0:8,9:9,8:9,17:9,5:9,6:9,1:11,13:9,7:9,16:12,10:13,14:7,18:14,19:15,16:16,10:17,11:18,16:19,11:20,16:21,10:22,12:23,12:24,4:25,12:26,4:27,10:28,12:29,12:30");fk(Sj,1,"G,AAAAY,AAAAoB,AAAAIG,AAAAAY,CAAAAg");fk(Uj,1,"Z");fk(Z,1,"g_f,AAgP,ABAwB,AAARG");fk(Qi,2,"B:P::");fk(Ri,4,"5.5.5.5:");for(var b=0;b<Z.length;b++){var d=Z[b],c=1;d[Wd]?c=2:d[gf]&&(c=0);nb[b]={firingOption:c,
state:void 0};ob[b]=[]}jg();vg();var n=w;if("interactive"==M.readyState&&!M.createEventObject||"complete"==M.readyState)Tf();else{O(M,"DOMContentLoaded",Tf);O(M,"readystatechange",Tf);if(M.createEventObject&&M.documentElement.doScroll){var q=!0;try{q=!n.frameElement}catch(v){}q&&Vf()}O(n,"load",Tf)}"complete"===M.readyState?Yf():O(w,
"load",Yf);fl();el()}};al.kb();var _vs="res_ts:1486646926947000,srv_cl:147853456,ds:live,cv:9";
})()
